# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('service_provider', models.CharField(choices=[('payu_paisa', 'PayU Money')], default='payu_paisa', max_length=30, unique=True)),
                ('key', models.CharField(max_length=100, verbose_name='Merchant Key')),
                ('base_url', models.CharField(max_length=100)),
                ('base_test_url', models.CharField(max_length=100)),
                ('surl', models.CharField(help_text='Callback Url when transaction is successfull.', max_length=100, verbose_name='Success Url')),
                ('furl', models.CharField(help_text='Callback Url when transaction fails.', max_length=100, verbose_name='Failure Url')),
                ('valid_param_list', models.CharField(help_text='Comma separated list of arguments.', max_length=500)),
                ('hash_params_list', models.CharField(help_text='Pipe separated list of arguments from which hash needs to be prepared.', max_length=500)),
                ('salt', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('txnid', models.CharField(help_text='Unique id to transact with payU', max_length=30, unique=True)),
                ('amount', models.FloatField()),
                ('productinfo', models.CharField(max_length=300)),
                ('firstname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('hash', models.CharField(help_text='This is an encrypted value generated to protect against data tampering during transaction', max_length=500)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentgateway.Configuration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('payuMoneyId', models.CharField(max_length=50)),
                ('hash', models.CharField(help_text='This is an encrypted value generated to protect against data tampering during transaction', max_length=500)),
                ('mode', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('amount', models.FloatField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('productinfo', models.CharField(max_length=50)),
                ('txn_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paymentgateway.TransactionRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
